kind: Job
apiVersion: batch/v1
metadata:
  name: unn-ss-pretrain
spec:
  template:
    spec:
      containers:
      - name: unn-ss-pretrain
        image: 'wickstrom91/xaitorch:v3'
        workingDir: /storage/experiments/LiverDec
        command: ["./unn-ss-pretrain.sh"]
        tty: true
        stdin: true
        volumeMounts:
        - name: storage
          mountPath: /storage
        env:
        - name: WANDB_API_KEY
          value: 9606bb31e8712b4f5c579967b8eb55906d9d6631
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0